# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  rres_config = debug_x64
  ggpo_config = debug_x64
  NightSkyEngineLite_config = debug_x64

else ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  rres_config = debug_x86
  ggpo_config = debug_x86
  NightSkyEngineLite_config = debug_x86

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  rres_config = release_x64
  ggpo_config = release_x64
  NightSkyEngineLite_config = release_x64

else ifeq ($(config),release_x86)
  raylib_config = release_x86
  rres_config = release_x86
  ggpo_config = release_x86
  NightSkyEngineLite_config = release_x86

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib rres ggpo NightSkyEngineLite

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C _build -f raylib.make config=$(raylib_config)
endif

rres:
ifneq (,$(rres_config))
	@echo "==== Building rres ($(rres_config)) ===="
	@${MAKE} --no-print-directory -C _build -f rres.make config=$(rres_config)
endif

ggpo:
ifneq (,$(ggpo_config))
	@echo "==== Building ggpo ($(ggpo_config)) ===="
	@${MAKE} --no-print-directory -C _build -f ggpo.make config=$(ggpo_config)
endif

NightSkyEngineLite: raylib ggpo
ifneq (,$(NightSkyEngineLite_config))
	@echo "==== Building NightSkyEngineLite ($(NightSkyEngineLite_config)) ===="
	@${MAKE} --no-print-directory -C _build -f NightSkyEngineLite.make config=$(NightSkyEngineLite_config)
endif

clean:
	@${MAKE} --no-print-directory -C _build -f raylib.make clean
	@${MAKE} --no-print-directory -C _build -f rres.make clean
	@${MAKE} --no-print-directory -C _build -f ggpo.make clean
	@${MAKE} --no-print-directory -C _build -f NightSkyEngineLite.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   rres"
	@echo "   ggpo"
	@echo "   NightSkyEngineLite"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"