# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -I../source -I../source/src -I../source/include -I../raylib-master/src -I../raylib-master/src/external -I../raylib-master/src/external/glfw/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x64)
TARGETDIR = ../_bin/Debug
TARGET = $(TARGETDIR)/NightSkyEngineLite.exe
OBJDIR = obj/x64/Debug/NightSkyEngineLite
DEFINES += -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c99
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++11
LIBS += ../_bin/Debug/raylib.lib -lwinmm -lkernel32 -lopengl32 -lgdi32
LDDEPS += ../_bin/Debug/raylib.lib
ALL_LDFLAGS += $(LDFLAGS) -L../_bin/Debug -L/usr/lib64 -m64

else ifeq ($(config),debug_x86)
TARGETDIR = ../_bin/Debug
TARGET = $(TARGETDIR)/NightSkyEngineLite.exe
OBJDIR = obj/x86/Debug/NightSkyEngineLite
DEFINES += -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -g -std=c99
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -g -std=c++11
LIBS += ../_bin/Debug/raylib.lib -lwinmm -lkernel32 -lopengl32 -lgdi32
LDDEPS += ../_bin/Debug/raylib.lib
ALL_LDFLAGS += $(LDFLAGS) -L../_bin/Debug -L/usr/lib32 -m32

else ifeq ($(config),release_x64)
TARGETDIR = ../_bin/Release
TARGET = $(TARGETDIR)/NightSkyEngineLite.exe
OBJDIR = obj/x64/Release/NightSkyEngineLite
DEFINES += -DNDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c99
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++11
LIBS += ../_bin/Release/raylib.lib -lwinmm -lkernel32 -lopengl32 -lgdi32
LDDEPS += ../_bin/Release/raylib.lib
ALL_LDFLAGS += $(LDFLAGS) -L../_bin/Release -L/usr/lib64 -m64 -mwindows -s

else ifeq ($(config),release_x86)
TARGETDIR = ../_bin/Release
TARGET = $(TARGETDIR)/NightSkyEngineLite.exe
OBJDIR = obj/x86/Release/NightSkyEngineLite
DEFINES += -DNDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -std=c99
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -std=c++11
LIBS += ../_bin/Release/raylib.lib -lwinmm -lkernel32 -lopengl32 -lgdi32
LDDEPS += ../_bin/Release/raylib.lib
ALL_LDFLAGS += $(LDFLAGS) -L../_bin/Release -L/usr/lib32 -m32 -mwindows -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/BattleActor.o
GENERATED += $(OBJDIR)/CString.o
GENERATED += $(OBJDIR)/FighterGameState.o
GENERATED += $(OBJDIR)/InputBuffer.o
GENERATED += $(OBJDIR)/PlayerCharacter.o
GENERATED += $(OBJDIR)/ScriptAnalyzer.o
GENERATED += $(OBJDIR)/State.o
GENERATED += $(OBJDIR)/StateMachine.o
GENERATED += $(OBJDIR)/Subroutine.o
GENERATED += $(OBJDIR)/android_native_app_glue.o
GENERATED += $(OBJDIR)/audio_module_playing.o
GENERATED += $(OBJDIR)/audio_multichannel_sound.o
GENERATED += $(OBJDIR)/audio_music_stream.o
GENERATED += $(OBJDIR)/audio_raw_stream.o
GENERATED += $(OBJDIR)/audio_sound_loading.o
GENERATED += $(OBJDIR)/audio_stream_effects.o
GENERATED += $(OBJDIR)/cocoa_time.o
GENERATED += $(OBJDIR)/context.o
GENERATED += $(OBJDIR)/core_2d_camera.o
GENERATED += $(OBJDIR)/core_2d_camera_mouse_zoom.o
GENERATED += $(OBJDIR)/core_2d_camera_platformer.o
GENERATED += $(OBJDIR)/core_3d_camera_first_person.o
GENERATED += $(OBJDIR)/core_3d_camera_free.o
GENERATED += $(OBJDIR)/core_3d_camera_mode.o
GENERATED += $(OBJDIR)/core_3d_picking.o
GENERATED += $(OBJDIR)/core_basic_screen_manager.o
GENERATED += $(OBJDIR)/core_basic_window.o
GENERATED += $(OBJDIR)/core_basic_window1.o
GENERATED += $(OBJDIR)/core_basic_window2.o
GENERATED += $(OBJDIR)/core_basic_window3.o
GENERATED += $(OBJDIR)/core_basic_window4.o
GENERATED += $(OBJDIR)/core_basic_window_web.o
GENERATED += $(OBJDIR)/core_custom_frame_control.o
GENERATED += $(OBJDIR)/core_custom_logging.o
GENERATED += $(OBJDIR)/core_drop_files.o
GENERATED += $(OBJDIR)/core_input_gamepad.o
GENERATED += $(OBJDIR)/core_input_gestures.o
GENERATED += $(OBJDIR)/core_input_keys.o
GENERATED += $(OBJDIR)/core_input_mouse.o
GENERATED += $(OBJDIR)/core_input_mouse_wheel.o
GENERATED += $(OBJDIR)/core_input_multitouch.o
GENERATED += $(OBJDIR)/core_loading_thread.o
GENERATED += $(OBJDIR)/core_random_values.o
GENERATED += $(OBJDIR)/core_scissor_test.o
GENERATED += $(OBJDIR)/core_smooth_pixelperfect.o
GENERATED += $(OBJDIR)/core_split_screen.o
GENERATED += $(OBJDIR)/core_storage_values.o
GENERATED += $(OBJDIR)/core_vr_simulator.o
GENERATED += $(OBJDIR)/core_window_flags.o
GENERATED += $(OBJDIR)/core_window_letterbox.o
GENERATED += $(OBJDIR)/core_window_should_close.o
GENERATED += $(OBJDIR)/core_world_screen.o
GENERATED += $(OBJDIR)/easings_testbed.o
GENERATED += $(OBJDIR)/egl_context.o
GENERATED += $(OBJDIR)/embedded_files_loading.o
GENERATED += $(OBJDIR)/examples_template.o
GENERATED += $(OBJDIR)/getopt.o
GENERATED += $(OBJDIR)/glx_context.o
GENERATED += $(OBJDIR)/init.o
GENERATED += $(OBJDIR)/input.o
GENERATED += $(OBJDIR)/linux_joystick.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/main1.o
GENERATED += $(OBJDIR)/main2.o
GENERATED += $(OBJDIR)/main3.o
GENERATED += $(OBJDIR)/models_animation.o
GENERATED += $(OBJDIR)/models_billboard.o
GENERATED += $(OBJDIR)/models_box_collisions.o
GENERATED += $(OBJDIR)/models_cubicmap.o
GENERATED += $(OBJDIR)/models_draw_cube_texture.o
GENERATED += $(OBJDIR)/models_first_person_maze.o
GENERATED += $(OBJDIR)/models_geometric_shapes.o
GENERATED += $(OBJDIR)/models_heightmap.o
GENERATED += $(OBJDIR)/models_loading.o
GENERATED += $(OBJDIR)/models_loading_gltf.o
GENERATED += $(OBJDIR)/models_loading_m3d.o
GENERATED += $(OBJDIR)/models_loading_vox.o
GENERATED += $(OBJDIR)/models_mesh_generation.o
GENERATED += $(OBJDIR)/models_mesh_picking.o
GENERATED += $(OBJDIR)/models_orthographic_projection.o
GENERATED += $(OBJDIR)/models_rlgl_solar_system.o
GENERATED += $(OBJDIR)/models_skybox.o
GENERATED += $(OBJDIR)/models_waving_cubes.o
GENERATED += $(OBJDIR)/models_yaw_pitch_roll.o
GENERATED += $(OBJDIR)/monitor.o
GENERATED += $(OBJDIR)/null_init.o
GENERATED += $(OBJDIR)/null_joystick.o
GENERATED += $(OBJDIR)/null_monitor.o
GENERATED += $(OBJDIR)/null_window.o
GENERATED += $(OBJDIR)/osmesa_context.o
GENERATED += $(OBJDIR)/platform.o
GENERATED += $(OBJDIR)/posix_module.o
GENERATED += $(OBJDIR)/posix_poll.o
GENERATED += $(OBJDIR)/posix_thread.o
GENERATED += $(OBJDIR)/posix_time.o
GENERATED += $(OBJDIR)/raudio.o
GENERATED += $(OBJDIR)/raylib_npp_parser.o
GENERATED += $(OBJDIR)/raylib_opengl_interop.o
GENERATED += $(OBJDIR)/raylib_parser.o
GENERATED += $(OBJDIR)/rcore.o
GENERATED += $(OBJDIR)/rglfw.o
GENERATED += $(OBJDIR)/rlgl_compute_shader.o
GENERATED += $(OBJDIR)/rlgl_standalone.o
GENERATED += $(OBJDIR)/rmodels.o
GENERATED += $(OBJDIR)/rshapes.o
GENERATED += $(OBJDIR)/rtext.o
GENERATED += $(OBJDIR)/rtextures.o
GENERATED += $(OBJDIR)/shaders_basic_lighting.o
GENERATED += $(OBJDIR)/shaders_custom_uniform.o
GENERATED += $(OBJDIR)/shaders_eratosthenes.o
GENERATED += $(OBJDIR)/shaders_fog.o
GENERATED += $(OBJDIR)/shaders_hot_reloading.o
GENERATED += $(OBJDIR)/shaders_julia_set.o
GENERATED += $(OBJDIR)/shaders_mesh_instancing.o
GENERATED += $(OBJDIR)/shaders_model_shader.o
GENERATED += $(OBJDIR)/shaders_multi_sample2d.o
GENERATED += $(OBJDIR)/shaders_palette_switch.o
GENERATED += $(OBJDIR)/shaders_postprocessing.o
GENERATED += $(OBJDIR)/shaders_raymarching.o
GENERATED += $(OBJDIR)/shaders_shapes_textures.o
GENERATED += $(OBJDIR)/shaders_simple_mask.o
GENERATED += $(OBJDIR)/shaders_spotlight.o
GENERATED += $(OBJDIR)/shaders_texture_drawing.o
GENERATED += $(OBJDIR)/shaders_texture_outline.o
GENERATED += $(OBJDIR)/shaders_texture_waves.o
GENERATED += $(OBJDIR)/shapes_basic_shapes.o
GENERATED += $(OBJDIR)/shapes_bouncing_ball.o
GENERATED += $(OBJDIR)/shapes_collision_area.o
GENERATED += $(OBJDIR)/shapes_colors_palette.o
GENERATED += $(OBJDIR)/shapes_draw_circle_sector.o
GENERATED += $(OBJDIR)/shapes_draw_rectangle_rounded.o
GENERATED += $(OBJDIR)/shapes_draw_ring.o
GENERATED += $(OBJDIR)/shapes_easings_ball_anim.o
GENERATED += $(OBJDIR)/shapes_easings_box_anim.o
GENERATED += $(OBJDIR)/shapes_easings_rectangle_array.o
GENERATED += $(OBJDIR)/shapes_following_eyes.o
GENERATED += $(OBJDIR)/shapes_lines_bezier.o
GENERATED += $(OBJDIR)/shapes_logo_raylib.o
GENERATED += $(OBJDIR)/shapes_logo_raylib_anim.o
GENERATED += $(OBJDIR)/shapes_rectangle_scaling.o
GENERATED += $(OBJDIR)/shapes_top_down_lights.o
GENERATED += $(OBJDIR)/text_codepoints_loading.o
GENERATED += $(OBJDIR)/text_draw_3d.o
GENERATED += $(OBJDIR)/text_font_filters.o
GENERATED += $(OBJDIR)/text_font_loading.o
GENERATED += $(OBJDIR)/text_font_sdf.o
GENERATED += $(OBJDIR)/text_font_spritefont.o
GENERATED += $(OBJDIR)/text_format_text.o
GENERATED += $(OBJDIR)/text_input_box.o
GENERATED += $(OBJDIR)/text_raylib_fonts.o
GENERATED += $(OBJDIR)/text_rectangle_bounds.o
GENERATED += $(OBJDIR)/text_unicode.o
GENERATED += $(OBJDIR)/text_writing_anim.o
GENERATED += $(OBJDIR)/textures_background_scrolling.o
GENERATED += $(OBJDIR)/textures_blend_modes.o
GENERATED += $(OBJDIR)/textures_bunnymark.o
GENERATED += $(OBJDIR)/textures_draw_tiled.o
GENERATED += $(OBJDIR)/textures_fog_of_war.o
GENERATED += $(OBJDIR)/textures_gif_player.o
GENERATED += $(OBJDIR)/textures_image_drawing.o
GENERATED += $(OBJDIR)/textures_image_generation.o
GENERATED += $(OBJDIR)/textures_image_loading.o
GENERATED += $(OBJDIR)/textures_image_processing.o
GENERATED += $(OBJDIR)/textures_image_text.o
GENERATED += $(OBJDIR)/textures_logo_raylib.o
GENERATED += $(OBJDIR)/textures_mouse_painting.o
GENERATED += $(OBJDIR)/textures_npatch_drawing.o
GENERATED += $(OBJDIR)/textures_particles_blending.o
GENERATED += $(OBJDIR)/textures_polygon.o
GENERATED += $(OBJDIR)/textures_raw_data.o
GENERATED += $(OBJDIR)/textures_sprite_anim.o
GENERATED += $(OBJDIR)/textures_sprite_button.o
GENERATED += $(OBJDIR)/textures_sprite_explosion.o
GENERATED += $(OBJDIR)/textures_srcrec_dstrec.o
GENERATED += $(OBJDIR)/textures_to_image.o
GENERATED += $(OBJDIR)/utils.o
GENERATED += $(OBJDIR)/vulkan.o
GENERATED += $(OBJDIR)/wgl_context.o
GENERATED += $(OBJDIR)/win32_init.o
GENERATED += $(OBJDIR)/win32_joystick.o
GENERATED += $(OBJDIR)/win32_module.o
GENERATED += $(OBJDIR)/win32_monitor.o
GENERATED += $(OBJDIR)/win32_thread.o
GENERATED += $(OBJDIR)/win32_time.o
GENERATED += $(OBJDIR)/win32_window.o
GENERATED += $(OBJDIR)/window.o
GENERATED += $(OBJDIR)/wl_init.o
GENERATED += $(OBJDIR)/wl_monitor.o
GENERATED += $(OBJDIR)/wl_window.o
GENERATED += $(OBJDIR)/x11_init.o
GENERATED += $(OBJDIR)/x11_monitor.o
GENERATED += $(OBJDIR)/x11_window.o
GENERATED += $(OBJDIR)/xkb_unicode.o
OBJECTS += $(OBJDIR)/BattleActor.o
OBJECTS += $(OBJDIR)/CString.o
OBJECTS += $(OBJDIR)/FighterGameState.o
OBJECTS += $(OBJDIR)/InputBuffer.o
OBJECTS += $(OBJDIR)/PlayerCharacter.o
OBJECTS += $(OBJDIR)/ScriptAnalyzer.o
OBJECTS += $(OBJDIR)/State.o
OBJECTS += $(OBJDIR)/StateMachine.o
OBJECTS += $(OBJDIR)/Subroutine.o
OBJECTS += $(OBJDIR)/android_native_app_glue.o
OBJECTS += $(OBJDIR)/audio_module_playing.o
OBJECTS += $(OBJDIR)/audio_multichannel_sound.o
OBJECTS += $(OBJDIR)/audio_music_stream.o
OBJECTS += $(OBJDIR)/audio_raw_stream.o
OBJECTS += $(OBJDIR)/audio_sound_loading.o
OBJECTS += $(OBJDIR)/audio_stream_effects.o
OBJECTS += $(OBJDIR)/cocoa_time.o
OBJECTS += $(OBJDIR)/context.o
OBJECTS += $(OBJDIR)/core_2d_camera.o
OBJECTS += $(OBJDIR)/core_2d_camera_mouse_zoom.o
OBJECTS += $(OBJDIR)/core_2d_camera_platformer.o
OBJECTS += $(OBJDIR)/core_3d_camera_first_person.o
OBJECTS += $(OBJDIR)/core_3d_camera_free.o
OBJECTS += $(OBJDIR)/core_3d_camera_mode.o
OBJECTS += $(OBJDIR)/core_3d_picking.o
OBJECTS += $(OBJDIR)/core_basic_screen_manager.o
OBJECTS += $(OBJDIR)/core_basic_window.o
OBJECTS += $(OBJDIR)/core_basic_window1.o
OBJECTS += $(OBJDIR)/core_basic_window2.o
OBJECTS += $(OBJDIR)/core_basic_window3.o
OBJECTS += $(OBJDIR)/core_basic_window4.o
OBJECTS += $(OBJDIR)/core_basic_window_web.o
OBJECTS += $(OBJDIR)/core_custom_frame_control.o
OBJECTS += $(OBJDIR)/core_custom_logging.o
OBJECTS += $(OBJDIR)/core_drop_files.o
OBJECTS += $(OBJDIR)/core_input_gamepad.o
OBJECTS += $(OBJDIR)/core_input_gestures.o
OBJECTS += $(OBJDIR)/core_input_keys.o
OBJECTS += $(OBJDIR)/core_input_mouse.o
OBJECTS += $(OBJDIR)/core_input_mouse_wheel.o
OBJECTS += $(OBJDIR)/core_input_multitouch.o
OBJECTS += $(OBJDIR)/core_loading_thread.o
OBJECTS += $(OBJDIR)/core_random_values.o
OBJECTS += $(OBJDIR)/core_scissor_test.o
OBJECTS += $(OBJDIR)/core_smooth_pixelperfect.o
OBJECTS += $(OBJDIR)/core_split_screen.o
OBJECTS += $(OBJDIR)/core_storage_values.o
OBJECTS += $(OBJDIR)/core_vr_simulator.o
OBJECTS += $(OBJDIR)/core_window_flags.o
OBJECTS += $(OBJDIR)/core_window_letterbox.o
OBJECTS += $(OBJDIR)/core_window_should_close.o
OBJECTS += $(OBJDIR)/core_world_screen.o
OBJECTS += $(OBJDIR)/easings_testbed.o
OBJECTS += $(OBJDIR)/egl_context.o
OBJECTS += $(OBJDIR)/embedded_files_loading.o
OBJECTS += $(OBJDIR)/examples_template.o
OBJECTS += $(OBJDIR)/getopt.o
OBJECTS += $(OBJDIR)/glx_context.o
OBJECTS += $(OBJDIR)/init.o
OBJECTS += $(OBJDIR)/input.o
OBJECTS += $(OBJDIR)/linux_joystick.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/main1.o
OBJECTS += $(OBJDIR)/main2.o
OBJECTS += $(OBJDIR)/main3.o
OBJECTS += $(OBJDIR)/models_animation.o
OBJECTS += $(OBJDIR)/models_billboard.o
OBJECTS += $(OBJDIR)/models_box_collisions.o
OBJECTS += $(OBJDIR)/models_cubicmap.o
OBJECTS += $(OBJDIR)/models_draw_cube_texture.o
OBJECTS += $(OBJDIR)/models_first_person_maze.o
OBJECTS += $(OBJDIR)/models_geometric_shapes.o
OBJECTS += $(OBJDIR)/models_heightmap.o
OBJECTS += $(OBJDIR)/models_loading.o
OBJECTS += $(OBJDIR)/models_loading_gltf.o
OBJECTS += $(OBJDIR)/models_loading_m3d.o
OBJECTS += $(OBJDIR)/models_loading_vox.o
OBJECTS += $(OBJDIR)/models_mesh_generation.o
OBJECTS += $(OBJDIR)/models_mesh_picking.o
OBJECTS += $(OBJDIR)/models_orthographic_projection.o
OBJECTS += $(OBJDIR)/models_rlgl_solar_system.o
OBJECTS += $(OBJDIR)/models_skybox.o
OBJECTS += $(OBJDIR)/models_waving_cubes.o
OBJECTS += $(OBJDIR)/models_yaw_pitch_roll.o
OBJECTS += $(OBJDIR)/monitor.o
OBJECTS += $(OBJDIR)/null_init.o
OBJECTS += $(OBJDIR)/null_joystick.o
OBJECTS += $(OBJDIR)/null_monitor.o
OBJECTS += $(OBJDIR)/null_window.o
OBJECTS += $(OBJDIR)/osmesa_context.o
OBJECTS += $(OBJDIR)/platform.o
OBJECTS += $(OBJDIR)/posix_module.o
OBJECTS += $(OBJDIR)/posix_poll.o
OBJECTS += $(OBJDIR)/posix_thread.o
OBJECTS += $(OBJDIR)/posix_time.o
OBJECTS += $(OBJDIR)/raudio.o
OBJECTS += $(OBJDIR)/raylib_npp_parser.o
OBJECTS += $(OBJDIR)/raylib_opengl_interop.o
OBJECTS += $(OBJDIR)/raylib_parser.o
OBJECTS += $(OBJDIR)/rcore.o
OBJECTS += $(OBJDIR)/rglfw.o
OBJECTS += $(OBJDIR)/rlgl_compute_shader.o
OBJECTS += $(OBJDIR)/rlgl_standalone.o
OBJECTS += $(OBJDIR)/rmodels.o
OBJECTS += $(OBJDIR)/rshapes.o
OBJECTS += $(OBJDIR)/rtext.o
OBJECTS += $(OBJDIR)/rtextures.o
OBJECTS += $(OBJDIR)/shaders_basic_lighting.o
OBJECTS += $(OBJDIR)/shaders_custom_uniform.o
OBJECTS += $(OBJDIR)/shaders_eratosthenes.o
OBJECTS += $(OBJDIR)/shaders_fog.o
OBJECTS += $(OBJDIR)/shaders_hot_reloading.o
OBJECTS += $(OBJDIR)/shaders_julia_set.o
OBJECTS += $(OBJDIR)/shaders_mesh_instancing.o
OBJECTS += $(OBJDIR)/shaders_model_shader.o
OBJECTS += $(OBJDIR)/shaders_multi_sample2d.o
OBJECTS += $(OBJDIR)/shaders_palette_switch.o
OBJECTS += $(OBJDIR)/shaders_postprocessing.o
OBJECTS += $(OBJDIR)/shaders_raymarching.o
OBJECTS += $(OBJDIR)/shaders_shapes_textures.o
OBJECTS += $(OBJDIR)/shaders_simple_mask.o
OBJECTS += $(OBJDIR)/shaders_spotlight.o
OBJECTS += $(OBJDIR)/shaders_texture_drawing.o
OBJECTS += $(OBJDIR)/shaders_texture_outline.o
OBJECTS += $(OBJDIR)/shaders_texture_waves.o
OBJECTS += $(OBJDIR)/shapes_basic_shapes.o
OBJECTS += $(OBJDIR)/shapes_bouncing_ball.o
OBJECTS += $(OBJDIR)/shapes_collision_area.o
OBJECTS += $(OBJDIR)/shapes_colors_palette.o
OBJECTS += $(OBJDIR)/shapes_draw_circle_sector.o
OBJECTS += $(OBJDIR)/shapes_draw_rectangle_rounded.o
OBJECTS += $(OBJDIR)/shapes_draw_ring.o
OBJECTS += $(OBJDIR)/shapes_easings_ball_anim.o
OBJECTS += $(OBJDIR)/shapes_easings_box_anim.o
OBJECTS += $(OBJDIR)/shapes_easings_rectangle_array.o
OBJECTS += $(OBJDIR)/shapes_following_eyes.o
OBJECTS += $(OBJDIR)/shapes_lines_bezier.o
OBJECTS += $(OBJDIR)/shapes_logo_raylib.o
OBJECTS += $(OBJDIR)/shapes_logo_raylib_anim.o
OBJECTS += $(OBJDIR)/shapes_rectangle_scaling.o
OBJECTS += $(OBJDIR)/shapes_top_down_lights.o
OBJECTS += $(OBJDIR)/text_codepoints_loading.o
OBJECTS += $(OBJDIR)/text_draw_3d.o
OBJECTS += $(OBJDIR)/text_font_filters.o
OBJECTS += $(OBJDIR)/text_font_loading.o
OBJECTS += $(OBJDIR)/text_font_sdf.o
OBJECTS += $(OBJDIR)/text_font_spritefont.o
OBJECTS += $(OBJDIR)/text_format_text.o
OBJECTS += $(OBJDIR)/text_input_box.o
OBJECTS += $(OBJDIR)/text_raylib_fonts.o
OBJECTS += $(OBJDIR)/text_rectangle_bounds.o
OBJECTS += $(OBJDIR)/text_unicode.o
OBJECTS += $(OBJDIR)/text_writing_anim.o
OBJECTS += $(OBJDIR)/textures_background_scrolling.o
OBJECTS += $(OBJDIR)/textures_blend_modes.o
OBJECTS += $(OBJDIR)/textures_bunnymark.o
OBJECTS += $(OBJDIR)/textures_draw_tiled.o
OBJECTS += $(OBJDIR)/textures_fog_of_war.o
OBJECTS += $(OBJDIR)/textures_gif_player.o
OBJECTS += $(OBJDIR)/textures_image_drawing.o
OBJECTS += $(OBJDIR)/textures_image_generation.o
OBJECTS += $(OBJDIR)/textures_image_loading.o
OBJECTS += $(OBJDIR)/textures_image_processing.o
OBJECTS += $(OBJDIR)/textures_image_text.o
OBJECTS += $(OBJDIR)/textures_logo_raylib.o
OBJECTS += $(OBJDIR)/textures_mouse_painting.o
OBJECTS += $(OBJDIR)/textures_npatch_drawing.o
OBJECTS += $(OBJDIR)/textures_particles_blending.o
OBJECTS += $(OBJDIR)/textures_polygon.o
OBJECTS += $(OBJDIR)/textures_raw_data.o
OBJECTS += $(OBJDIR)/textures_sprite_anim.o
OBJECTS += $(OBJDIR)/textures_sprite_button.o
OBJECTS += $(OBJDIR)/textures_sprite_explosion.o
OBJECTS += $(OBJDIR)/textures_srcrec_dstrec.o
OBJECTS += $(OBJDIR)/textures_to_image.o
OBJECTS += $(OBJDIR)/utils.o
OBJECTS += $(OBJDIR)/vulkan.o
OBJECTS += $(OBJDIR)/wgl_context.o
OBJECTS += $(OBJDIR)/win32_init.o
OBJECTS += $(OBJDIR)/win32_joystick.o
OBJECTS += $(OBJDIR)/win32_module.o
OBJECTS += $(OBJDIR)/win32_monitor.o
OBJECTS += $(OBJDIR)/win32_thread.o
OBJECTS += $(OBJDIR)/win32_time.o
OBJECTS += $(OBJDIR)/win32_window.o
OBJECTS += $(OBJDIR)/window.o
OBJECTS += $(OBJDIR)/wl_init.o
OBJECTS += $(OBJDIR)/wl_monitor.o
OBJECTS += $(OBJDIR)/wl_window.o
OBJECTS += $(OBJDIR)/x11_init.o
OBJECTS += $(OBJDIR)/x11_monitor.o
OBJECTS += $(OBJDIR)/x11_window.o
OBJECTS += $(OBJDIR)/xkb_unicode.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking NightSkyEngineLite
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning NightSkyEngineLite
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/BattleActor.o: ../source/Battle/Actors/BattleActor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FighterGameState.o: ../source/Battle/Actors/FighterGameState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PlayerCharacter.o: ../source/Battle/Actors/PlayerCharacter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/InputBuffer.o: ../source/Battle/InputBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ScriptAnalyzer.o: ../source/Battle/NightSkyScript/ScriptAnalyzer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/State.o: ../source/Battle/State.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StateMachine.o: ../source/Battle/StateMachine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Subroutine.o: ../source/Battle/Subroutine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CString.o: ../source/CString.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: ../source/main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/audio_module_playing.o: ../source/raylib-master/examples/audio/audio_module_playing.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/audio_multichannel_sound.o: ../source/raylib-master/examples/audio/audio_multichannel_sound.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/audio_music_stream.o: ../source/raylib-master/examples/audio/audio_music_stream.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/audio_raw_stream.o: ../source/raylib-master/examples/audio/audio_raw_stream.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/audio_sound_loading.o: ../source/raylib-master/examples/audio/audio_sound_loading.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/audio_stream_effects.o: ../source/raylib-master/examples/audio/audio_stream_effects.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_2d_camera.o: ../source/raylib-master/examples/core/core_2d_camera.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_2d_camera_mouse_zoom.o: ../source/raylib-master/examples/core/core_2d_camera_mouse_zoom.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_2d_camera_platformer.o: ../source/raylib-master/examples/core/core_2d_camera_platformer.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_3d_camera_first_person.o: ../source/raylib-master/examples/core/core_3d_camera_first_person.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_3d_camera_free.o: ../source/raylib-master/examples/core/core_3d_camera_free.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_3d_camera_mode.o: ../source/raylib-master/examples/core/core_3d_camera_mode.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_3d_picking.o: ../source/raylib-master/examples/core/core_3d_picking.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_basic_screen_manager.o: ../source/raylib-master/examples/core/core_basic_screen_manager.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_basic_window.o: ../source/raylib-master/examples/core/core_basic_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_basic_window_web.o: ../source/raylib-master/examples/core/core_basic_window_web.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_custom_frame_control.o: ../source/raylib-master/examples/core/core_custom_frame_control.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_custom_logging.o: ../source/raylib-master/examples/core/core_custom_logging.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_drop_files.o: ../source/raylib-master/examples/core/core_drop_files.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_input_gamepad.o: ../source/raylib-master/examples/core/core_input_gamepad.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_input_gestures.o: ../source/raylib-master/examples/core/core_input_gestures.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_input_keys.o: ../source/raylib-master/examples/core/core_input_keys.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_input_mouse.o: ../source/raylib-master/examples/core/core_input_mouse.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_input_mouse_wheel.o: ../source/raylib-master/examples/core/core_input_mouse_wheel.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_input_multitouch.o: ../source/raylib-master/examples/core/core_input_multitouch.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_loading_thread.o: ../source/raylib-master/examples/core/core_loading_thread.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_random_values.o: ../source/raylib-master/examples/core/core_random_values.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_scissor_test.o: ../source/raylib-master/examples/core/core_scissor_test.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_smooth_pixelperfect.o: ../source/raylib-master/examples/core/core_smooth_pixelperfect.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_split_screen.o: ../source/raylib-master/examples/core/core_split_screen.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_storage_values.o: ../source/raylib-master/examples/core/core_storage_values.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_vr_simulator.o: ../source/raylib-master/examples/core/core_vr_simulator.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_window_flags.o: ../source/raylib-master/examples/core/core_window_flags.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_window_letterbox.o: ../source/raylib-master/examples/core/core_window_letterbox.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_window_should_close.o: ../source/raylib-master/examples/core/core_window_should_close.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_world_screen.o: ../source/raylib-master/examples/core/core_world_screen.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/examples_template.o: ../source/raylib-master/examples/examples_template.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_animation.o: ../source/raylib-master/examples/models/models_animation.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_billboard.o: ../source/raylib-master/examples/models/models_billboard.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_box_collisions.o: ../source/raylib-master/examples/models/models_box_collisions.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_cubicmap.o: ../source/raylib-master/examples/models/models_cubicmap.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_draw_cube_texture.o: ../source/raylib-master/examples/models/models_draw_cube_texture.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_first_person_maze.o: ../source/raylib-master/examples/models/models_first_person_maze.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_geometric_shapes.o: ../source/raylib-master/examples/models/models_geometric_shapes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_heightmap.o: ../source/raylib-master/examples/models/models_heightmap.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_loading.o: ../source/raylib-master/examples/models/models_loading.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_loading_gltf.o: ../source/raylib-master/examples/models/models_loading_gltf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_loading_m3d.o: ../source/raylib-master/examples/models/models_loading_m3d.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_loading_vox.o: ../source/raylib-master/examples/models/models_loading_vox.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_mesh_generation.o: ../source/raylib-master/examples/models/models_mesh_generation.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_mesh_picking.o: ../source/raylib-master/examples/models/models_mesh_picking.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_orthographic_projection.o: ../source/raylib-master/examples/models/models_orthographic_projection.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_rlgl_solar_system.o: ../source/raylib-master/examples/models/models_rlgl_solar_system.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_skybox.o: ../source/raylib-master/examples/models/models_skybox.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_waving_cubes.o: ../source/raylib-master/examples/models/models_waving_cubes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/models_yaw_pitch_roll.o: ../source/raylib-master/examples/models/models_yaw_pitch_roll.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/easings_testbed.o: ../source/raylib-master/examples/others/easings_testbed.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/embedded_files_loading.o: ../source/raylib-master/examples/others/embedded_files_loading.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/raylib_opengl_interop.o: ../source/raylib-master/examples/others/raylib_opengl_interop.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rlgl_compute_shader.o: ../source/raylib-master/examples/others/rlgl_compute_shader.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rlgl_standalone.o: ../source/raylib-master/examples/others/rlgl_standalone.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_basic_lighting.o: ../source/raylib-master/examples/shaders/shaders_basic_lighting.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_custom_uniform.o: ../source/raylib-master/examples/shaders/shaders_custom_uniform.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_eratosthenes.o: ../source/raylib-master/examples/shaders/shaders_eratosthenes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_fog.o: ../source/raylib-master/examples/shaders/shaders_fog.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_hot_reloading.o: ../source/raylib-master/examples/shaders/shaders_hot_reloading.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_julia_set.o: ../source/raylib-master/examples/shaders/shaders_julia_set.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_mesh_instancing.o: ../source/raylib-master/examples/shaders/shaders_mesh_instancing.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_model_shader.o: ../source/raylib-master/examples/shaders/shaders_model_shader.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_multi_sample2d.o: ../source/raylib-master/examples/shaders/shaders_multi_sample2d.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_palette_switch.o: ../source/raylib-master/examples/shaders/shaders_palette_switch.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_postprocessing.o: ../source/raylib-master/examples/shaders/shaders_postprocessing.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_raymarching.o: ../source/raylib-master/examples/shaders/shaders_raymarching.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_shapes_textures.o: ../source/raylib-master/examples/shaders/shaders_shapes_textures.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_simple_mask.o: ../source/raylib-master/examples/shaders/shaders_simple_mask.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_spotlight.o: ../source/raylib-master/examples/shaders/shaders_spotlight.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_texture_drawing.o: ../source/raylib-master/examples/shaders/shaders_texture_drawing.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_texture_outline.o: ../source/raylib-master/examples/shaders/shaders_texture_outline.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shaders_texture_waves.o: ../source/raylib-master/examples/shaders/shaders_texture_waves.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_basic_shapes.o: ../source/raylib-master/examples/shapes/shapes_basic_shapes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_bouncing_ball.o: ../source/raylib-master/examples/shapes/shapes_bouncing_ball.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_collision_area.o: ../source/raylib-master/examples/shapes/shapes_collision_area.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_colors_palette.o: ../source/raylib-master/examples/shapes/shapes_colors_palette.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_draw_circle_sector.o: ../source/raylib-master/examples/shapes/shapes_draw_circle_sector.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_draw_rectangle_rounded.o: ../source/raylib-master/examples/shapes/shapes_draw_rectangle_rounded.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_draw_ring.o: ../source/raylib-master/examples/shapes/shapes_draw_ring.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_easings_ball_anim.o: ../source/raylib-master/examples/shapes/shapes_easings_ball_anim.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_easings_box_anim.o: ../source/raylib-master/examples/shapes/shapes_easings_box_anim.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_easings_rectangle_array.o: ../source/raylib-master/examples/shapes/shapes_easings_rectangle_array.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_following_eyes.o: ../source/raylib-master/examples/shapes/shapes_following_eyes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_lines_bezier.o: ../source/raylib-master/examples/shapes/shapes_lines_bezier.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_logo_raylib.o: ../source/raylib-master/examples/shapes/shapes_logo_raylib.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_logo_raylib_anim.o: ../source/raylib-master/examples/shapes/shapes_logo_raylib_anim.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_rectangle_scaling.o: ../source/raylib-master/examples/shapes/shapes_rectangle_scaling.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shapes_top_down_lights.o: ../source/raylib-master/examples/shapes/shapes_top_down_lights.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_codepoints_loading.o: ../source/raylib-master/examples/text/text_codepoints_loading.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_draw_3d.o: ../source/raylib-master/examples/text/text_draw_3d.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_font_filters.o: ../source/raylib-master/examples/text/text_font_filters.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_font_loading.o: ../source/raylib-master/examples/text/text_font_loading.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_font_sdf.o: ../source/raylib-master/examples/text/text_font_sdf.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_font_spritefont.o: ../source/raylib-master/examples/text/text_font_spritefont.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_format_text.o: ../source/raylib-master/examples/text/text_format_text.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_input_box.o: ../source/raylib-master/examples/text/text_input_box.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_raylib_fonts.o: ../source/raylib-master/examples/text/text_raylib_fonts.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_rectangle_bounds.o: ../source/raylib-master/examples/text/text_rectangle_bounds.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_unicode.o: ../source/raylib-master/examples/text/text_unicode.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/text_writing_anim.o: ../source/raylib-master/examples/text/text_writing_anim.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_background_scrolling.o: ../source/raylib-master/examples/textures/textures_background_scrolling.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_blend_modes.o: ../source/raylib-master/examples/textures/textures_blend_modes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_bunnymark.o: ../source/raylib-master/examples/textures/textures_bunnymark.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_draw_tiled.o: ../source/raylib-master/examples/textures/textures_draw_tiled.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_fog_of_war.o: ../source/raylib-master/examples/textures/textures_fog_of_war.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_gif_player.o: ../source/raylib-master/examples/textures/textures_gif_player.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_image_drawing.o: ../source/raylib-master/examples/textures/textures_image_drawing.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_image_generation.o: ../source/raylib-master/examples/textures/textures_image_generation.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_image_loading.o: ../source/raylib-master/examples/textures/textures_image_loading.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_image_processing.o: ../source/raylib-master/examples/textures/textures_image_processing.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_image_text.o: ../source/raylib-master/examples/textures/textures_image_text.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_logo_raylib.o: ../source/raylib-master/examples/textures/textures_logo_raylib.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_mouse_painting.o: ../source/raylib-master/examples/textures/textures_mouse_painting.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_npatch_drawing.o: ../source/raylib-master/examples/textures/textures_npatch_drawing.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_particles_blending.o: ../source/raylib-master/examples/textures/textures_particles_blending.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_polygon.o: ../source/raylib-master/examples/textures/textures_polygon.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_raw_data.o: ../source/raylib-master/examples/textures/textures_raw_data.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_sprite_anim.o: ../source/raylib-master/examples/textures/textures_sprite_anim.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_sprite_button.o: ../source/raylib-master/examples/textures/textures_sprite_button.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_sprite_explosion.o: ../source/raylib-master/examples/textures/textures_sprite_explosion.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_srcrec_dstrec.o: ../source/raylib-master/examples/textures/textures_srcrec_dstrec.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textures_to_image.o: ../source/raylib-master/examples/textures/textures_to_image.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/raylib_parser.o: ../source/raylib-master/parser/raylib_parser.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main1.o: ../source/raylib-master/projects/4coder/main.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_basic_window1.o: ../source/raylib-master/projects/CMake/core_basic_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_basic_window2.o: ../source/raylib-master/projects/CodeBlocks/core_basic_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_basic_window3.o: ../source/raylib-master/projects/Geany/core_basic_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/raylib_npp_parser.o: ../source/raylib-master/projects/Notepad++/raylib_npp_parser/raylib_npp_parser.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/android_native_app_glue.o: ../source/raylib-master/projects/VS2019-Android/raylib_android/raylib_android.NativeActivity/android_native_app_glue.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main2.o: ../source/raylib-master/projects/VS2019-Android/raylib_android/raylib_android.NativeActivity/main.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main3.o: ../source/raylib-master/projects/VSCode/main.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_basic_window4.o: ../source/raylib-master/projects/scripts/core_basic_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/getopt.o: ../source/raylib-master/src/external/glfw/deps/getopt.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cocoa_time.o: ../source/raylib-master/src/external/glfw/src/cocoa_time.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/context.o: ../source/raylib-master/src/external/glfw/src/context.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/egl_context.o: ../source/raylib-master/src/external/glfw/src/egl_context.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/glx_context.o: ../source/raylib-master/src/external/glfw/src/glx_context.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/init.o: ../source/raylib-master/src/external/glfw/src/init.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/input.o: ../source/raylib-master/src/external/glfw/src/input.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/linux_joystick.o: ../source/raylib-master/src/external/glfw/src/linux_joystick.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/monitor.o: ../source/raylib-master/src/external/glfw/src/monitor.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/null_init.o: ../source/raylib-master/src/external/glfw/src/null_init.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/null_joystick.o: ../source/raylib-master/src/external/glfw/src/null_joystick.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/null_monitor.o: ../source/raylib-master/src/external/glfw/src/null_monitor.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/null_window.o: ../source/raylib-master/src/external/glfw/src/null_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/osmesa_context.o: ../source/raylib-master/src/external/glfw/src/osmesa_context.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/platform.o: ../source/raylib-master/src/external/glfw/src/platform.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/posix_module.o: ../source/raylib-master/src/external/glfw/src/posix_module.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/posix_poll.o: ../source/raylib-master/src/external/glfw/src/posix_poll.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/posix_thread.o: ../source/raylib-master/src/external/glfw/src/posix_thread.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/posix_time.o: ../source/raylib-master/src/external/glfw/src/posix_time.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan.o: ../source/raylib-master/src/external/glfw/src/vulkan.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wgl_context.o: ../source/raylib-master/src/external/glfw/src/wgl_context.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/win32_init.o: ../source/raylib-master/src/external/glfw/src/win32_init.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/win32_joystick.o: ../source/raylib-master/src/external/glfw/src/win32_joystick.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/win32_module.o: ../source/raylib-master/src/external/glfw/src/win32_module.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/win32_monitor.o: ../source/raylib-master/src/external/glfw/src/win32_monitor.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/win32_thread.o: ../source/raylib-master/src/external/glfw/src/win32_thread.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/win32_time.o: ../source/raylib-master/src/external/glfw/src/win32_time.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/win32_window.o: ../source/raylib-master/src/external/glfw/src/win32_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/window.o: ../source/raylib-master/src/external/glfw/src/window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wl_init.o: ../source/raylib-master/src/external/glfw/src/wl_init.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wl_monitor.o: ../source/raylib-master/src/external/glfw/src/wl_monitor.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wl_window.o: ../source/raylib-master/src/external/glfw/src/wl_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/x11_init.o: ../source/raylib-master/src/external/glfw/src/x11_init.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/x11_monitor.o: ../source/raylib-master/src/external/glfw/src/x11_monitor.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/x11_window.o: ../source/raylib-master/src/external/glfw/src/x11_window.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/xkb_unicode.o: ../source/raylib-master/src/external/glfw/src/xkb_unicode.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/raudio.o: ../source/raylib-master/src/raudio.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rcore.o: ../source/raylib-master/src/rcore.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rglfw.o: ../source/raylib-master/src/rglfw.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rmodels.o: ../source/raylib-master/src/rmodels.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rshapes.o: ../source/raylib-master/src/rshapes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rtext.o: ../source/raylib-master/src/rtext.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rtextures.o: ../source/raylib-master/src/rtextures.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: ../source/raylib-master/src/utils.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif